### ISSUE TITLE
gitpod status failed to detect US cluster failure

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod-status#13]
See https://github.com/gitpod-io/gitpod/issues/1511#event-3339764440 gitpod's US cluster was offline for around 5 hours which is not reflected in gitpod status:
![image](https://user-images.githubusercontent.com/11302521/82028949-8e025600-9696-11ea-9d04-7ff2eb38ccb2.png)

**Comment by gtsiolis** [comment]
Closing this as is no longer relevant. Possibly the same issue caused https://github.com/gitpod-io/gitpod-status/issues/20.
