### ISSUE TITLE
Incident is visible only after you visit incident history

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod-status#20]
### Problem

We recently pushed https://github.com/gitpod-io/gitpod-status/commit/cb3279e06dfd9a17d0030a021f6ddbbbb3c80a1a which contained a new incident.

However this didn't update the landing page in `status.gitpod.io`. The incident is visible only after you visit incident history ([`/history`](https://status.gitpod.io/history)) and then go back to `status.gitpod.io`.

| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/98835087-a803d200-2448-11eb-90d3-8cbb6fe6713e.png) | ![image](https://user-images.githubusercontent.com/120486/98835105-acc88600-2448-11eb-84a3-316ac069bd9a.png) |

**Comment by gtsiolis** [comment]
For more context, @corneliusludmann mentioned caching could be related to the issue here. See relevant [discussion](https://typefox.slack.com/archives/CGVQAPNPL/p1605111765310000) (internal).

**Comment by meysholdt** [comment]
fixed by disabling GCP Cloud CDN for status.gitpod.io.
